### PR TITLE
Make backups readable by a remote user

### LINKED ISSUE #47: Unhelpful permissions on blobstoragebackup directory
The blobstoragebackups directory is not readable by anyone other than plone_daemon.
That is not helpful if I am for instance trying to pull backups on to another server (remember that plone_daemon is not given an external login, and it's recommended to turn off root's login)

### PR DESCRIPTION
**Pull request by djowett**
Resolves #47 (see that issue for details)

### CODE REVIEW

**Comment by smcmahon** [comment]
I've been pondering this, and I don't think this will be seen as desirable by everyone. It's a slight decrease in file-system security, and the backup problem can be solved in other ways (e.g., the rsync daemon).

Why not set up an plone_rsync_backup_options variable that can be used to add whatever rsync options might be desired?

**Comment by djowett** [comment]
@smcmahon thanks for thinking!  I don't mind setting a variable, if you don't mind yet another one.  Rsync daemon only helps when "pushing" out the backups, right?  I'm looking to "pull" them at the moment.

**Comment by do3cc** [comment]
This sets the group permissions, maybe this is just a matter of documenting the consequences of choosing the right plone user?

**Comment by djowett** [comment]
@do3cc thanks, but I don't *think* so.   I seem to recall advice somewhere which said either that: 

* plone_daemon user should not login OR
* password based logins should be disabled (and since plone_daemon doesn't have an ssh key generated [here](https://github.com/plone/ansible.plone_server/blob/299aade15da464a302acdd2f4ab64fe5e605d6e5/tasks/main.yml#L45) that stops login as that user) 

In which case the only user that can read backups is unable to login to scp them down.  As Steve says there is an rsync option - but that's, if I understand correctly, only applicable if you are "pushing" backups out to a backup server, and I am not doing that.

Is my thinking wonky?

**Comment by smcmahon** [comment]
There are lots of options for doing backups without changing the file system security. It's not like these files are being held open. And, if folks want to change the ownership/permissions for the backups, they won't necessarily want to use the plone_group to do it. Allowing them to set their own rsync options seems like an ideal compromise to me.

**Pull request closed without merging**
