### PR TITLE
Add missing dependency `curl`.

### PR DESCRIPTION
**Pull request by htgoebel**

### CODE REVIEW

**Comment by htgoebel** [comment]
Pinging: Is anybody going to merge this?

**Comment by do3cc** [comment]
Hi,

can you add a changelog entry?

**Comment by do3cc** [comment]
I interpret our patch policy in such a way that this does not constitute a copyrightable "creative work."
as it only adds:
- Missing or updated "import" statements;

https://plone.org/foundation/materials/foundation-resolutions/patch-policy-052011

As such, I'd merge the PR when the Changelog entry is there

**Comment by htgoebel** [comment]
It his History-note okay?

**Comment by do3cc** [comment]
Uhm, barely, because no one would know what it means. It merge it anyway. Else the changelog will be longer when the changes. I just need to kick the right people to get write access. Timezones are our enemy here right now

**Comment by smcmahon** [comment]
cron was already in the list. Someone else must have added it.
curl was added in a separate commit.

**Pull request closed without merging**
